### ISSUE TITLE
Install the CA-Certificates components

### ISSUE THREAD

**Issue by fangzhengjin** [bitnami/bitnami-docker-bitnami-shell#1]
Currently, only the curl component is provided, which causes an error when accessing an HTTPS site.

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Can you install the CA-Certificates component to avoid this problem.

**Comment by alemorcuq** [comment]
Hi, @fangzhengjin.

The problem with adding the `ca-certificates` to the image is that it would also add the `openssl` package to it, which is a sensitive package from a security point of view. Since the purpose of this image is to serve as a very basic image to perform certain actions and it is included in many of our charts by default, we don't like the idea of including this package by default.

However, you can extend the image yourself to install the packages you need.

**Comment by fangzhengjin** [comment]
OK, thank you for your reply！



---Original---
From: "Alejandro ***@***.***&gt;
Date: Fri, Mar 12, 2021 22:53 PM
To: ***@***.***&gt;;
Cc: "ZhengJin ***@***.******@***.***&gt;;
Subject: Re: [bitnami/bitnami-docker-bitnami-shell] Install the CA-Certificates components (#1)




 
Hi, @fangzhengjin.
 
The problem with adding the ca-certificates to the image is that it would also add the openssl package to it, which is a sensitive package from a security point of view. Since the purpose of this image is to serve as a very basic image to perform certain actions and it is included in many of our charts by default, we don't like the idea of including this package by default.
 
However, you can extend the image yourself to install the packages you need.
